# Numpy 100道练习

##  导入numpy库并简写为 np

In [1]:
import numpy as np

## 打印numpy的版本和配置说明

In [2]:
print(np.__version__)

1.15.1


In [4]:
np.show_config()

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Van/AppData/Local/Continuum/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'C:/Users/Van/AppData/Local/Continuum/anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Van/AppData/Local/Continuum/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTo

##  创建一个长度为10的空向量

In [9]:
data1 = np.empty(10)
print(data1)

[           nan 0.0000000e+000 1.0491809e-311 2.0236929e-320
 0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000
 0.0000000e+000 0.0000000e+000]


In [10]:
data2 = np.zeros(10)
print(data2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


空向量应该用np.empty 还是 np.zeros?

## 如何找到任何一个数组的内存大小？

In [24]:
data = np.zeros((100,100))
print(data.size)  #数据的数目
print(data.itemsize) #单条数据大小
print('%d bytes' % (data.size*data.itemsize)) #整个数据大小

10000
8
80000 bytes


## 如何从命令行得到numpy中add函数的说明文档?

In [25]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

## 创建一个长度为10并且除了第五个值为1的空向量 

In [28]:
data = np.zeros(10)
data[4] = 1
data

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

小结：用np.zeros构造，用索引作替换。需要注意索引是从0开始

## 创建一个值域范围从10到49的向量

In [29]:
data = np.arange(10,50)
data

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## 反转一个向量(第一个元素变为最后一个) 

In [30]:
data = np.arange(10)
data = data[::-1]
data

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

小结：使用列表中步进值实现，步进值：隔多少个取一个值，此处用-1实现倒序。

## 创建一个 3x3 并且值从0到8的矩阵

In [31]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

小结：用reshape函数

## 找到数组[1,2,0,0,4,0]中非0元素的位置索引

In [32]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


小结，：使用nonzero函数

## 创建一个 3x3 的单位矩阵

In [40]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

小结：使用eye或identity函数

## 创建一个 3x3x3的随机数组

In [42]:
np.random.random((3,3,3))

array([[[0.85821605, 0.46245805, 0.96191479],
        [0.70836819, 0.68870324, 0.51473696],
        [0.36719045, 0.61859277, 0.50125821]],

       [[0.53959776, 0.24184873, 0.28275008],
        [0.17656591, 0.73607719, 0.15686161],
        [0.43973047, 0.09029507, 0.28864486]],

       [[0.90537349, 0.46830224, 0.20255274],
        [0.2869832 , 0.82516277, 0.42312667],
        [0.94774467, 0.72436831, 0.90912204]]])

小结：使用numpy.random中的函数

numpy.random模块填补了Python内建的random模块的不足，可以高效地生成多种概率分布下的完整样本值数组。

## 创建一个 10x10 的随机数组并找到它的最大值和最小值

In [48]:
data = np.random.random((10,10))
maxdata = data.max()
mindata = data.min()
print(maxdata)
print(mindata)

0.997277026153016
0.001719459856677319


## 创建一个长度为30的随机向量并找到它的平均值

In [49]:
data = np.random.random(30)
meandata  = data.mean()
print(meandata)

0.49576767020925216


## 创建一个二维数组，其中边界值为1，其余值为0

In [50]:
data = np.ones((10,10))
data[1:-1,1:-1] = 0 
data

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## 对于一个存在在数组，如何添加一个用0填充的边界?

In [53]:
np.info(np.pad)

 pad(array, pad_width, mode, **kwargs)

Pads an array.

Parameters
----------
array : array_like of rank N
    Input array
pad_width : {sequence, array_like, int}
    Number of values padded to the edges of each axis.
    ((before_1, after_1), ... (before_N, after_N)) unique pad widths
    for each axis.
    ((before, after),) yields same before and after pad for each axis.
    (pad,) or int is a shortcut for before = after = pad width for all
    axes.
mode : str or function
    One of the following string values or a user supplied function.

    'constant'
        Pads with a constant value.
    'edge'
        Pads with the edge values of array.
    'linear_ramp'
        Pads with the linear ramp between end_value and the
        array edge value.
    'maximum'
        Pads with the maximum value of all or part of the
        vector along each axis.
    'mean'
        Pads with the mean value of all or part of the
        vector along each axis.
    'median'
        Pads with the med

In [56]:
data = np.ones((5,5))
data = np.pad(data, pad_width=((1,1),(1,1)), mode='constant', constant_values=0)
print(data)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


小结：使用pad函数，该函数的作用是填补

可见https://www.cnblogs.com/hezhiyao/p/8177541.html

## 以下表达式运行的结果分别是什么?

In [58]:
0 * np.nan

nan

In [59]:
np.nan == np.nan

False

In [63]:
np.inf > np.nan  #np.inf 表示正无穷

False

In [61]:
np.nan - np.nan

nan

In [62]:
0.3 == 3 * 0.1

False

小结：这里涉及到常会疑惑np.nan问题
- np.nan不是一个“空”对象，用 i is None判断是False；
- 对某个值是否为空值进行判断，只能用np.isnan(i)函数，万万不可用 i == np.nan()来做.因为空值并不能用判断相等的“==”正确识别
- np.nan非空对象，其类型为基本数据类型float

可看：[用pandas或numpy处理数据中的空值（np.isnan()/pd.isnull()）](https://blog.csdn.net/weixin_41712499/article/details/82719987)


## 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置

In [74]:
np.diag(np.arange(1,5), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

小结：使用diag函数

可参考：

[实验楼 - Python Numpy 100题实验（三）](https://blog.csdn.net/sinat_34328764/article/details/82926058)

[numpy.diag()结构及用法||参数详解](https://blog.csdn.net/The_Time_Runner/article/details/89918383)

## 创建一个8x8 的矩阵，并且设置成棋盘样式

data = np.zeros((8,8),dtype=int)
data[1::2,::2] = 1
data[::2,1::2] = 1
print(data)

## 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么?

In [79]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

参考资料：

[如何通过numpy获得二维或多维数组的最大、小值索引](https://www.cnblogs.com/subic/p/8710946.html)

[numpy.unravel_index 说明](https://blog.csdn.net/dn_mug/article/details/70256109)




##  用tile函数去创建一个 8x8的棋盘样式矩阵

In [81]:
data = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(data)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


小结： 使用tile函数，将原矩阵横向、纵向地复制。

[图解Numpy的tile函数](https://www.jianshu.com/p/9519f1984c70)

## 对一个5x5的随机矩阵做归一化

In [83]:
data = np.random.random((5,5))
datamax = data.max() 
datamin = data.min()
data = (data - datamin)/(datamax - datamin)
print(data)

[[0.62049637 0.96773478 0.95052979 0.72043721 0.14948987]
 [0.64303004 0.64151183 0.51198646 0.20214748 0.10748814]
 [0.         0.72314425 0.90942384 0.2663694  0.04514883]
 [0.71187611 0.02276168 0.36774255 1.         0.82756736]
 [0.72169586 0.85422806 0.19377563 0.87934342 0.01142075]]


## 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？

In [84]:
 color = np.dtype([("r", np.ubyte, 1),
                   ("g", np.ubyte, 1),
                   ("b", np.ubyte, 1),
                   ("a", np.ubyte, 1)])
 color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

小结：np.dtype用于自定义数据类型

##  一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？

In [88]:
data = np.dot(np.ones((5,3)),np.ones((3,2)))
data

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

## 给定一个一维数组，对其在3到8之间的所有元素取反

In [94]:
data = np.arange(11)
data[(3 < data) & (data <= 8)] *= -1
print(data)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


## 下面脚本运行后的结果是什么?

In [98]:
print(sum(range(5),-1))

10


In [99]:
from numpy import *
print(sum(range(5),-1))

10


## 考虑一个整数向量Z,下列表达合法的是哪个?

In [109]:
Z = np.arange(5)
Z

array([0, 1, 2, 3, 4])

In [107]:
Z ** Z

array([  1,   1,   4,  27, 256], dtype=int32)

In [113]:
2 << Z >> 2 

array([0, 1, 2, 4, 8], dtype=int32)

In [104]:
 Z <- Z 

array([False, False, False, False, False])

In [110]:
1j*Z 

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [111]:
Z/1/1 

array([0., 1., 2., 3., 4.])

In [112]:
 Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

## 下列表达式的结果分别是什么?

In [114]:
print(np.array(0) / np.array(0))

nan


C:\Users\Van\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [115]:
print(np.array(0) // np.array(0))

0


C:\Users\Van\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


In [116]:
print(np.array([np.nan]).astype(int).astype(float))

[-2.14748365e+09]


## 如何从零位对浮点数组做舍入 ? 

In [117]:
data = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(data)), data))

[ 9.  4.  6.  9. -7.  3. -7.  9.  7.  9.]


## 如何找到两个数组中的共同元素?

In [118]:
data1 = np.random.randint(0,10,10)
data2 = np.random.randint(0,10,10)
print(np.intersect1d(data1,data2))

[0 3 7 9]


## 如何忽略所有的 numpy 警告(尽管不建议这么做)?

In [2]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

Z

array([inf])

In [3]:

_ = np.seterr(**defaults)


with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0
Z

array([inf])

## 下面的表达式是正确的吗?

In [4]:
np.sqrt(-1) == np.emath.sqrt(-1) 

C:\Users\Van\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

## 如何得到昨天，今天，明天的日期?

In [5]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-06-21
Today is 2019-06-22
Tomorrow is 2019-06-23


##  如何得到所有与2016年7月对应的日期？

In [6]:
data = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(data)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


## 如何直接在位计算(A+B)\*(-A/2)(不建立副本)?

In [7]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)

array([3., 3., 3.])

In [8]:
np.divide(A,2,out=A)

array([0.5, 0.5, 0.5])

In [9]:
np.negative(A,out=A)

array([-0.5, -0.5, -0.5])

In [10]:
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

## 用五种不同的方法去提取一个随机数组的整数部分

In [12]:
data = np.random.uniform(0,10,10)

In [13]:
print (data - data%1)

[9. 5. 8. 6. 0. 0. 4. 2. 9. 0.]


In [14]:
print (np.floor(data))   #向下取整

[9. 5. 8. 6. 0. 0. 4. 2. 9. 0.]


In [15]:
print (np.ceil(data)-1)  #计算大于等于改值的最小整数 向上取整

[9. 5. 8. 6. 0. 0. 4. 2. 9. 0.]


In [16]:
print (data.astype(int))

[9 5 8 6 0 0 4 2 9 0]


In [17]:
print (np.trunc(data))

[9. 5. 8. 6. 0. 0. 4. 2. 9. 0.]


## 创建一个5x5的矩阵，其中每行的数值范围从0到4 

In [18]:
data = np.zeros((5,5))
data += np.arange(5)
print (data)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## 通过考虑一个可生成10个整数的函数，来构建一个数组

In [19]:
def generate():
    for x in range(10):
         yield x
data = np.fromiter(generate(),dtype=float,count=-1)
print (data)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


小结：使用生成器

## 创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1 

In [20]:
data = np.linspace(0,1,11,endpoint=False)[1:]
print (data)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


## 创建一个长度为10的随机向量，并将其排序

In [21]:
data = np.random.random(10)
data.sort()
print (data)

[0.22457012 0.31219542 0.35608245 0.39197793 0.42867295 0.54234808
 0.5514992  0.7394509  0.78544501 0.87565914]


## 对于一个小数组，如何用比 np.sum更快的方式对其求和？

In [22]:
data = np.arange(10)
np.add.reduce(data)

45

[np.sum和np.add.reduce有什么区别？](https://cloud.tencent.com/developer/ask/119244)

## 对于两个随机数组A和B，检查它们是否相等

In [23]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


In [24]:
equal = np.array_equal(A,B)
print(equal)

False


## 创建一个只读数组(read-only) 

In [25]:
data = np.zeros(10)
data.flags.writeable = False
data[0] = 1

ValueError: assignment destination is read-only

## 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式

In [26]:
data = np.random.random((10,2))
X,Y = data[:,0], data[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)

[1.10601372 0.81816166 1.01772848 0.16135325 1.20534482 1.16354268
 0.84849566 0.94093878 0.4334883  1.26318177]
[0.60129325 0.21899796 1.28355673 0.04897298 0.69273714 0.75807405
 0.6523739  0.29678004 0.49479359 0.87346019]


## 创建一个长度为10的向量，并将向量中最大值替换为1

In [27]:
data= np.random.random(10)
data[data.argmax()] = 0
print (data)

[0.86870689 0.5217209  0.85611533 0.75331369 0.01474158 0.
 0.53206173 0.42158236 0.66772073 0.34106872]


## 创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域

In [ ]:
data = np.zeros((5,5), [('x',float),('y',float)])
data['x'], data['y'] = np.meshgrid(np.linspace(0,1,5),
np.linspace(0,1,5))
print(data)

[numpy.linspace使用详解](https://www.cnblogs.com/antflow/p/7220798.html)

## 给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj))

In [29]:
X = np.arange(10)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

33961.93294480225


## 打印每个numpy标量类型的最小值和最大值？

In [30]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


## 如何打印一个数组中的所有数值?

In [33]:
data = np.zeros((8,8))
print (data)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


## 给定标量时，如何找到数组中最接近标量的值？

In [34]:
data = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(data-v)).argmin()
print (data[index])

68


## 创建一个表示位置(x,y)和颜色(r,g,b)的结构化数组

In [3]:
data = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print (data)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


## 对一个表示坐标形状为(100,2)的随机向量，找到点与点的距离

In [5]:
data = np.random.random((10,2))
import scipy
import scipy.spatial
D = scipy.spatial.distance.cdist(data,data)
print (D)

[[0.         0.60760782 0.39355777 0.60190235 0.46717538 0.23720214
  0.32906753 0.07268578 0.69689727 0.48745214]
 [0.60760782 0.         0.21554131 0.78665992 0.86952135 0.6590785
  0.81954904 0.54420426 0.13101863 0.12290774]
 [0.39355777 0.21554131 0.         0.68449571 0.70737889 0.47601085
  0.63284999 0.33299249 0.32072883 0.0939127 ]
 [0.60190235 0.78665992 0.68449571 0.         0.2750679  0.37136311
  0.39753681 0.56181289 0.77353452 0.73292518]
 [0.46717538 0.86952135 0.70737889 0.2750679  0.         0.24688395
  0.15981809 0.45981016 0.89658326 0.78208222]
 [0.23720214 0.6590785  0.47601085 0.37136311 0.24688395 0.
  0.1606171  0.21576274 0.70958145 0.55858192]
 [0.32906753 0.81954904 0.63284999 0.39753681 0.15981809 0.1606171
  0.         0.33885351 0.86910342 0.71751653]
 [0.07268578 0.54420426 0.33299249 0.56181289 0.45981016 0.21576274
  0.33885351 0.         0.62866356 0.42625715]
 [0.69689727 0.13101863 0.32072883 0.77353452 0.89658326 0.70958145
  0.86910342 0.6286635

## 如何将32位的浮点数(float)转换为对应的整数

In [6]:
data = np.arange(10, dtype=np.int32)
data = data.astype(np.float32, copy=False)
print (data)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


## 如何读取以下文件?

## 对于numpy数组，enumerate的等价操作是什么？

In [7]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print (index, value)
for index in np.ndindex(Z.shape):
    print (index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


## 生成一个通用的二维Gaussian-like数组

In [8]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print (G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

## 对一个二维数组，如何在其内部随机放置p个元素?

In [9]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## 减去一个矩阵中的每一行的平均值

In [10]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)

[[-0.38906518 -0.36722611 -0.33449781 -0.0131848   0.0612888   0.28578131
   0.01267943  0.54569558 -0.18565868  0.38418745]
 [-0.27089394  0.31941282  0.11501209  0.16112414 -0.32134659  0.17059804
  -0.1006472   0.32161579 -0.26910085 -0.1257743 ]
 [-0.31125403 -0.29822174 -0.06410963 -0.01351534  0.36530824  0.2727107
  -0.05201164 -0.16340264  0.10556204  0.15893402]
 [-0.1732214  -0.19038187  0.02173864  0.41166892  0.22724128  0.06668685
  -0.40809123 -0.31892991  0.35642912  0.00685961]
 [-0.11181414  0.42562916  0.44666635  0.12191333 -0.01391678 -0.4585514
  -0.36146071 -0.23105879  0.39727056 -0.21467759]]


## 如何通过第n列对一个数组进行排序?

In [12]:
data = np.random.randint(0,10,(3,3))
print (data)
print (data[data[:,1].argsort()])

[[0 1 4]
 [0 4 7]
 [8 2 5]]
[[0 1 4]
 [8 2 5]
 [0 4 7]]


## 如何检查一个二维数组是否有空列？

In [13]:
data = np.random.randint(0,3,(3,10))
print ((~data.any(axis=0)).any())

False


小结：any(x)判断x对象是否为空对象，如果都为空、0、false，则返回false，如果不都为空、0、false，则返回true

## 从数组中的给定值中找出最近的值

In [14]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print (m)

0.49133712707574584


## 如何用迭代器(iterator)计算两个分别具有形状(1,3)和(3,1)的数组?

In [15]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: 
    z[...] = x + y
print (it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


[numpy np.nditer()](https://blog.csdn.net/joyeishappy/article/details/83783020)

## 创建一个具有name属性的数组类

In [17]:
class NamedArray(np.ndarray):
     def __new__(cls, array, name="no name"):
         obj = np.asarray(array).view(cls)
         obj.name = name
         return obj
     def __array_finalize__(self, obj):
         if obj is None: return
         self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


## 考虑一个给定的向量，如何对由第二个向量索引的每个元素加1(小心重复的索引)? 

In [19]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
np.add.at(Z, I, 1)
print(Z)

[2. 5. 3. 4. 3. 5. 3. 3. 1. 1.]


## 根据索引列表(I)，如何将向量(X)的元素累加到数组(F)?

In [20]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print (F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


## 考虑一个(dtype=ubyte) 的 (w,h,3)图像，计算其唯一颜色的数量

In [22]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
# #Note that we should compute 256*256 first. 
# #Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print (n)

8


## 考虑一个四维数组，如何一次性计算出最后两个轴(axis)的和？

In [23]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print (sum)

[[48 52 53 32]
 [53 60 54 62]
 [62 67 58 54]]


##  考虑一个一维向量D，如何使用相同大小的向量S来计算D子集的均值？

In [24]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print (D_means)

[0.55655248 0.38365925 0.34690324 0.40011106 0.52883997 0.69124217
 0.30826818 0.48936904 0.52268045 0.45568124]


In [25]:
import pandas as pd
print(pd.Series(D).groupby(S).mean())

0    0.556552
1    0.383659
2    0.346903
3    0.400111
4    0.528840
5    0.691242
6    0.308268
7    0.489369
8    0.522680
9    0.455681
dtype: float64


## 如何获得点积 dot prodcut的对角线?

In [27]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
# # slow version
np.diag(np.dot(A, B))

array([1.06104384, 0.93616436, 1.31607951, 0.9506885 , 1.11950011])

In [28]:
# # Fast version
np.sum(A * B.T, axis=1)

array([1.06104384, 0.93616436, 1.31607951, 0.9506885 , 1.11950011])

 ##  考虑一个向量[1,2,3,4,5],如何建立一个新的向量，在这个新向量中每个值之间有3个连续的零？

In [4]:
data = np.array([1,2,3,4,5])
n = 3
data0 = np.zeros(len(data) + (len(data)-1)*(n))
data0[::n+1] = data
print (data0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


## 考虑一个维度(5,5,3)的数组，如何将其与一个(5,5)的数组相乘？

In [7]:
A = np.ones((5,5,3))
B = 3*np.ones((5,5))
print (A * B[:,:,None])

[[[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]]


## 如何对一个数组中任意两行做交换?

In [8]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print (A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


## 考虑一个可以描述10个三角形的triplets，找到可以分割全部三角形的line segment

In [9]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print (G)

[( 0, 38) ( 0, 99) ( 3,  6) ( 3, 22) ( 3, 28) ( 3, 38) ( 6, 18) ( 6, 38)
 ( 6, 71) ( 8, 85) ( 8, 92) (16, 59) (16, 96) (18, 71) (22, 28) (32, 38)
 (32, 90) (38, 90) (38, 99) (51, 57) (51, 69) (53, 77) (53, 96) (57, 69)
 (59, 96) (72, 72) (72, 78) (77, 96) (85, 92)]


 ## 给定一个二进制的数组C，如何产生一个数组A满足np.bincount(A)==C

In [10]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print (A)

[1 1 2 3 4 4 6]


## 如何通过滑动窗口计算一个数组的平均数?

In [11]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)

print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


## Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

In [13]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)

Z = rolling(np.arange(10), 3)

print (Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


## 如何对布尔值取反，或者原位(in-place)改变浮点数的符号(sign)？

In [14]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

array([0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1])

## 考虑两组点集P0和P1去描述一组线(二维)和一个点p,如何计算点p到每一条线 i (P0[i],P1[i])的距离？

In [15]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))

print (distance(P0, P1, p))

[13.20760713  3.1675237  17.61491012 12.82061343  9.04302379 11.54108814
  4.46725076  4.07567239  4.96454199  6.67498512]


## 考虑两组点集P0和P1去描述一组线(二维)和一组点集P，如何计算每一个点 j(P[j]) 到每一条线 i (P0[i],P1[i])的距离？

In [16]:
# # based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[7.28178784e+00 9.27715530e-01 1.59720490e+01 4.79015117e+00
  1.69169476e+00 1.38804627e+01 1.02374563e+00 1.40732046e+01
  3.45703370e+00 1.55454576e+00]
 [6.22327966e+00 1.74296434e+00 7.71603398e+00 4.69426797e+00
  1.00221893e+00 9.17113806e+00 1.55780485e-01 8.16373241e+00
  3.44911890e+00 5.63229825e+00]
 [6.67320477e-01 7.31398723e+00 6.53821841e+00 8.93693563e-01
  6.56193247e+00 4.48247689e+00 5.70246664e+00 4.11311938e+00
  3.44643038e-01 2.81754850e+00]
 [3.82324374e+00 4.10029628e+00 5.60140362e+00 2.47409426e+00
  3.05424144e+00 6.38277125e+00 2.57636026e+00 5.38672422e+00
  3.60713596e+00 5.96055497e+00]
 [1.81467566e+00 6.12175005e+00 5.41838163e+00 4.24674608e-01
  5.11702588e+00 4.80309563e+00 4.57786449e+00 4.07766533e+00
  2.25818301e+00 4.70952650e+00]
 [7.85123556e+00 1.58674956e+01 5.11924584e+00 9.50798046e+00
  1.51704807e+01 2.52249139e+00 1.42008904e+01 1.84990776e+00
  4.77639289e+00 1.87013320e+00]
 [6.57615356e+00 1.63472187e+00 1.58048030e+01 4.08258217e

## Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)

In [17]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print (Z)
print (R)

[[4 0 1 2 3 6 7 5 2 7]
 [3 6 5 8 2 8 9 6 9 6]
 [9 7 2 6 7 6 4 8 5 8]
 [0 1 2 2 7 3 8 8 9 7]
 [3 1 0 6 1 6 9 5 3 7]
 [6 4 6 2 5 8 4 2 8 1]
 [6 4 9 0 0 0 0 3 3 5]
 [2 0 0 0 6 6 1 3 5 7]
 [6 3 3 5 7 5 8 4 6 4]
 [3 9 3 1 0 1 8 9 5 3]]
[[0 0 0 0 0]
 [0 4 0 1 2]
 [0 3 6 5 8]
 [0 9 7 2 6]
 [0 0 1 2 2]]


C:\Users\Van\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


## 考虑一个数组Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14],如何生成一个数组R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ...,[11,12,13,14]]?

In [4]:
from numpy.lib import stride_tricks
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print (R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


## 计算一个矩阵的秩

In [5]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print (rank)

10


## 如何找到一个数组中出现频率最高的值？

In [7]:
Z = np.random.randint(0,10,50)
print (np.bincount(Z).argmax())

6


## 从一个10x10的矩阵中提取出连续的3x3区块

In [8]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print (C)

[[[[1 0 2]
   [3 3 4]
   [3 1 2]]

  [[0 2 1]
   [3 4 4]
   [1 2 1]]

  [[2 1 3]
   [4 4 2]
   [2 1 2]]

  [[1 3 1]
   [4 2 3]
   [1 2 4]]

  [[3 1 0]
   [2 3 3]
   [2 4 3]]

  [[1 0 3]
   [3 3 2]
   [4 3 0]]

  [[0 3 0]
   [3 2 1]
   [3 0 0]]

  [[3 0 4]
   [2 1 0]
   [0 0 2]]]


 [[[3 3 4]
   [3 1 2]
   [2 4 3]]

  [[3 4 4]
   [1 2 1]
   [4 3 4]]

  [[4 4 2]
   [2 1 2]
   [3 4 2]]

  [[4 2 3]
   [1 2 4]
   [4 2 2]]

  [[2 3 3]
   [2 4 3]
   [2 2 3]]

  [[3 3 2]
   [4 3 0]
   [2 3 3]]

  [[3 2 1]
   [3 0 0]
   [3 3 0]]

  [[2 1 0]
   [0 0 2]
   [3 0 0]]]


 [[[3 1 2]
   [2 4 3]
   [3 4 0]]

  [[1 2 1]
   [4 3 4]
   [4 0 4]]

  [[2 1 2]
   [3 4 2]
   [0 4 0]]

  [[1 2 4]
   [4 2 2]
   [4 0 4]]

  [[2 4 3]
   [2 2 3]
   [0 4 2]]

  [[4 3 0]
   [2 3 3]
   [4 2 2]]

  [[3 0 0]
   [3 3 0]
   [2 2 4]]

  [[0 0 2]
   [3 0 0]
   [2 4 0]]]


 [[[2 4 3]
   [3 4 0]
   [4 2 0]]

  [[4 3 4]
   [4 0 4]
   [2 0 0]]

  [[3 4 2]
   [0 4 0]
   [0 0 3]]

  [[4 2 2]
   [4 0 4]
   [0 3 4]]

  [[2 2 3]
   

## 创建一个满足 Z[i,j] == Z[j,i]的子类

In [9]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)
    
S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print (S)

[[ 0  7  8  3  8]
 [ 7  5  5 17  9]
 [ 8  5  7 42 13]
 [ 3 17 42  2 14]
 [ 8  9 13 14  5]]


## 考虑p个 nxn 矩阵和一组形状为(n,1)的向量，如何直接计算p个矩阵的乘积(n,1)？

In [10]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print (S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


## 对于一个16x16的数组，如何得到一个区域(block-sum)的和(区域大小为4x4)? 

In [11]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                        np.arange(0, Z.shape[1], k), axis=1)
print (S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


## 如何利用numpy数组实现Game of Life?

In [12]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
        Z[1:-1,0:-2]                + Z[1:-1,2:] +
        Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print (Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


## 如何找到一个数组的第n个最大值?

In [13]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5


print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


In [14]:
print (Z[np.argpartition(-Z,n)[:n]])

[9998 9999 9997 9996 9995]


## 给定任意个数向量，创建笛卡尔积(每一个元素的每一种组合)

In [15]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
        return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]
 [2 0 0]
 [2 0 1]
 [2 1 0]
 [2 1 1]
 [3 0 0]
 [3 0 1]
 [3 1 0]
 [3 1 1]]


## 如何从一个正常数组创建记录数组(record array)? 

In [16]:
Z = np.array([("Hello", 2.5, 3),
               ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                                names='col1, col2, col3',
                                formats = 'S8, f8, i8')
print (R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


## 考虑一个大向量Z, 用三种不同的方法计算它的立方

In [17]:
x = np.random.rand()
np.power(x,3)

0.5102699079801637

In [18]:
x*x*x

0.5102699079801638

In [20]:
np.einsum('i,i,i->i',x,x,x)

ValueError: einstein sum subscripts string contains too many subscripts for operand 0

[NumPy中einsum的基本介绍](https://cloud.tencent.com/developer/article/1369762)

##  考虑两个形状分别为(8,3) 和(2,2)的数组A和B. 如何在数组A中找到满足包含B中元素的行？(不考虑B中每行元素顺序)？

In [21]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print (rows) 

[0 2 6 7]


## 考虑一个10x3的矩阵，分解出有不全相同值的行 (如 [2,2,3]) 

In [22]:
Z = np.random.randint(0,5,(10,3))
print (Z)

# # solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print (U)

[[0 1 3]
 [2 3 2]
 [3 3 0]
 [3 3 2]
 [0 0 4]
 [0 2 2]
 [1 0 3]
 [0 4 2]
 [2 3 1]
 [0 2 4]]
[[0 1 3]
 [2 3 2]
 [3 3 0]
 [3 3 2]
 [0 0 4]
 [0 2 2]
 [1 0 3]
 [0 4 2]
 [2 3 1]
 [0 2 4]]


## 将一个整数向量转换为matrix binary的表现形式

In [23]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


## 给定一个二维数组，如何提取出唯一的(unique)行?

In [29]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_ , idx = np.unique(T, return_index=True)
uZ = Z[idx]
print (uZ)

[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 1 0]
 [1 1 1]]


## 考虑两个向量A和B，写出用einsum等式对应的inner, outer, sum, mul函数

In [30]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
print ('sum')
print (np.einsum('i->', A))# np.sum(A)

sum
4.390361595939363


In [31]:
print ('A * B')
print (np.einsum('i,i->i', A, B)) # A * B

A * B
[0.02491149 0.07852662 0.07272958 0.49025924 0.48171966 0.09356595
 0.00386087 0.31991003 0.06293769 0.36600456]


In [32]:
print ('inner')
print (np.einsum('i,i', A, B))    # np.inner(A, B)

inner
1.994425672412875


In [33]:
print ('outer')
print (np.einsum('i,j->ij', A, B))    # np.outer(A, B)

outer
[[2.49114891e-02 5.34044934e-01 5.42882313e-01 4.79749136e-01
  7.08318294e-01 7.17826151e-01 2.40554695e-01 7.08546905e-01
  7.05815875e-02 2.79292577e-01]
 [3.66301567e-03 7.85266169e-02 7.98260759e-02 7.05428966e-02
  1.04151984e-01 1.05550031e-01 3.53714551e-02 1.04185599e-01
  1.03784025e-02 4.10675204e-02]
 [3.33737557e-03 7.15456434e-02 7.27295812e-02 6.42716715e-02
  9.48929291e-02 9.61666904e-02 3.22269520e-02 9.49235560e-02
  9.45576817e-03 3.74166402e-02]
 [2.54572375e-02 5.45744521e-01 5.54775505e-01 4.90259238e-01
  7.23835774e-01 7.33551925e-01 2.45824646e-01 7.24069394e-01
  7.21278533e-02 2.85411178e-01]
 [1.69420359e-02 3.63198218e-01 3.69208425e-01 3.26272230e-01
  4.81719657e-01 4.88185848e-01 1.63598662e-01 4.81875133e-01
  4.80017788e-02 1.89943879e-01]
 [3.24711926e-03 6.96107559e-02 7.07626752e-02 6.25335021e-02
  9.23266353e-02 9.35659489e-02 3.13554031e-02 9.23564339e-02
  9.20004544e-03 3.64047408e-02]
 [3.99826507e-04 8.57135915e-03 8.71319806e-03 7.699

## 考虑一个由两个向量描述的路径(X,Y)，如何用等距样例(equidistant samples)对其进行采样(sample)?

In [34]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

## Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.

In [35]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                 [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print (X[M])

[[2. 0. 1. 1.]]


## 对于一个一维数组X，计算它boostrapped之后的95%置信区间的平均值

In [36]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print (confint)

[-0.4849946  -0.01823546]
